### ISSUE TITLE
Investigate random failures of TestInbound

### ISSUE THREAD

**Issue by tjaskula** [vlingo-net/vlingo-net-wire#16]
From time to time `TestInbound` fails with the following message:

```
Assert.Equal() Failure
                  ↓ (pos 8)
Expected: Message-1
Actual:   Message-2
                  ↑ (pos 8)
```

at:

```
at Vlingo.Wire.Tests.Fdx.Inbound.InboundStreamTest.TestInbound() in C:\projects\vlingo-net-wire\src\Vlingo.Wire.Tests\Fdx\Inbound\InboundStreamTest.cs:line 36
```

More details here: https://ci.appveyor.com/project/VlingoNetOwner/vlingo-net-wire/builds/23642914/tests

**Comment by tjaskula** [comment]
Seems like sometimes messages are received out of order: https://ci.appveyor.com/project/VlingoNetOwner/vlingo-net-wire/build/tests

```
Assert.Equal() Failure
                  ↓ (pos 8)
Expected: Message-1
Actual:   Message-3
                  ↑ (pos 8)
```

**Comment by tjaskula** [comment]
This should be fixed with #42

**Comment by tjaskula** [comment]
It's not fixed in #42 but should be addressed by #48

**Comment by mihaj** [comment]
@tjaskula Is this issue fixed, so this can be closed?

**Comment by tjaskula** [comment]
Yes, I'll close that
