### ISSUE TITLE
GetAllNetworkInterfaces does not return correct Network interface when running a test

### ISSUE THREAD

**Issue by mihaj** [vlingo-net/vlingo-net-wire#53]
This is environment specific, on my machine the test `TestMulticastPublishSubscribe` fails because it can not find appropriate network interface.

https://github.com/vlingo-net/vlingo-net-wire/blob/11255f7fe93a2b48cf87c825262e25392b1c6d3c/src/Vlingo.Wire/Multicast/MulticastSubscriber.cs#L195

**Comment by VaughnVernon** [comment]
@mihaj This may be obvious, but I have seen this when my wifi is turned off. When the problem with networking is isolated it's sometimes not exactly the software.

**Comment by mihaj** [comment]
Agree. I will close it.
